### ISSUE TITLE
RNG-seed from defineModel() not used consistently

### ISSUE THREAD

**Issue by schumaki** [weirichs/eatModel#1]
Using TAM for IRT-estimation, a seed can be specified in `defineModel()`.
However, the internal function `getTamInfit()` at [line 2070](https://github.com/weirichs/eatModel/blob/008cb8b51986d8d4c29fe2e474a15a979625ff4f/R/eatModel.r#L2070) doesn't use this seed, although the function `TAM::tam.fit()` in line 2072 has an optional argument `seed`.

As a result, two runs of `itemFromRes(getResults(runModel(model1)))` will allways get different results for `infit` if `software = "tam"` is used in the definition of `model1`. This is rather annoying, espescially in reproducing results ("Kontrollskalierung")...

**Comment by weirichs** [comment]
Thanks for the hint. An additional seed argument was added to the `getResults` function (which in turn calls `tam.fit`). Please install from Github. 
Note: to fix the seed for model calibration, set the seed argument in `defineModel()`. To fix the seed for infit estimation, set the seed argument in `getResults()`.
