### ISSUE TITLE
restructure eatModel.r

### ISSUE THREAD

**Issue by grewered** [weirichs/eatModel#7]
ideas how to restructe eatModel.R. right now it has almost 100 functions and isn't very programmer friendly when editing the code. 

- [x] give user functions their own file
- [x] group functions with similar functionality (getx, checkx, etc.)
- [x] group functions called by multiple functions
- [x] group functions called by a singular (user) function

**Comment by grewered** [comment]
@weirichs what do you think?

**getConquest.R**
![grafik](https://github.com/user-attachments/assets/67c51890-f2b8-4625-b67f-b2ae2ad07af9)
![grafik](https://github.com/user-attachments/assets/4bd4b5da-3591-4abb-9496-7c86a40c1443)

**getTam.R**
![grafik](https://github.com/user-attachments/assets/6f45f46e-e207-4e90-bc81-8036d09d5cbc)

**fromRes.R**
![grafik](https://github.com/user-attachments/assets/0762cf6c-b383-46ba-8b96-adbb7069fc21)

**get.R**
![grafik](https://github.com/user-attachments/assets/23b80c8b-0ebf-41d8-90a8-fc25cecf43ae)

There are several check and prep functions that maybe could go into 1 file. 
And the others have no name-theming, so I still have to look at them, but that could take a while.

**Comment by grewered** [comment]
@weirichs ok, so I got an overview now.
most functions are either only called by one of the 6 larger functions (or their specific help functions) OR they are called by multiple functions, but can ne categorized by name. There are very few exceptions that I would leave in eatModel.R for now, unless you have an idea for a different name. 

I would propose:

- **splitModels.R**, chooseCores.R (as is)
- **defineModel.R**, checkLinking.R (as is), gen.syntax.R (with help functions), defineModel_help.R (div. help functions)
- checkModels.R (div. check-functions for splitModels and defineModels)
- **runModel.R** (incl. help functions)
- **getResults.R**, getQ3.R, getConquest.R, getTam.R
- get.R (mainly getResults related)
- **equat1pl.R**, equat1pl_help.R
- **transformToBista.R**, transformToBista_help.R
- plotICC.R
- eatModel.R (now with only 3 or so functions)

**Comment by weirichs** [comment]
Good idea, thank you!
